package seleniumNotes;

import java.time.Duration;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
//********** What is a web=table? *****************
/* It is like any other table with header, body, rows, columns, elements but generated by using a HTML language
 * Web-table in HTML DOM are written with "table" tag-name
 * If table has a header it is written with "thead" tag-name
 * Each element in the row is written with "th" tag-name
 * Table body is written with "tbody" tag-name
 * Each row in the table is written with "tr" tag-name
 * Each element in the row is written with "td" tag-name 
 */

//********** How to handle webtable using selenium? *****************
/* There are three ways by means of which we can handle web-table using Selenium. Ways depends on degree of insight we need to handle.
 * 
 * 1. By using FindElement method and providing xpath of "table" tagname.
 * 
 * 2. By using FindElements method and providing xpath of "table" tagname and iterating by using "foreach" loop
 * 
 * 3. By using getElement method and providing xpath of each element by using nested for loop to change index value of xpath
 * 
 * all methods are demonstrated below
 */

public class T08_WebTable {

	public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver","E:\\Testing\\AskWorkspace\\workspace1\\My_Selenium_Notes\\SoftFiles\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population");
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
		
//**********Reading and printing web-table on the console using getElement method************
	
	// Here xpath of "table" tagname has to be provided to getElement() method.
	// The entire table will be considered as one web-element.
	// We can not deal with row/column/individual element of the webtable
		WebElement tableAsElement = driver.findElement(By.xpath("//table[@class='wikitable sortable jquery-tablesorter']"));
		String tableAsElementText = tableAsElement.getText(); //table webelement converted into text.
		System.out.println(tableAsElementText); //table printed

		
//Printing web-table elements by providing xpath of header & body, using getElements() method
		
	//Here xpath of such element has to be provided who has further sub-elements. 
	// these are with tagname thead(header)/tbody(table Body)/tr(table row)
	// by using foreach loop subelements can be handled altogether
		List<WebElement> headerData = driver.findElements(By.xpath("//table[@class='wikitable sortable jquery-tablesorter']/thead"));
		for (WebElement elements : headerData) {
			System.out.println(elements.getText()); // table header printed
		}
		
		List<WebElement> bodyData = driver.findElements(By.xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody"));
		for (WebElement elements : bodyData) {
			System.out.println(elements.getText());  //table body printed
		}
	

//Printing web-table elements by providing xpath of each element with the help of indexing and nested for loop, using getElement() method
	//Here we first need to get the count of rows and columns to be used in nested for loop
		 int headerColCount = driver.findElements(By.xpath("//table[@class='wikitable sortable jquery-tablesorter']/thead/tr/th")).size(); //header count taken separately 
	//Header is a single row; here we provided indexing to "th" and 
		 for (int i=1; i<=headerColCount; i++) {
			 String headerText = driver.findElement(By.xpath("//table[@class='wikitable sortable jquery-tablesorter']/thead/tr/th["+i+"]")).getText(); //getting header element text
			 
			 System.out.print(headerText+" | "); //printing content of header
		 }
		 System.out.println();  //blank line
		 
	//Table body has many rows and each row has many elements. Hence we need Nested for loop
	//Firstly we get count of number of rows in table body and number of cells in each row with the help of size() method
		 int bodyRowCount = driver.findElements(By.xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr")).size();
		 int RowCellCounr = driver.findElements(By.xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr[1]/td")).size();
	//We use Upper loop for each row and Inner loop for each cell in the row
		 for(int row=1; row<=bodyRowCount; row++) {
			 for(int col=1; col<=RowCellCounr; col++) {
				 String tableElement = driver.findElement(By.xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr["+row+"]/td["+col+"]")).getText(); //getting cell element text
				 
				 System.out.print(tableElement+" | "); //printing cell text
			 }
			 System.out.println(); // next Line after each row printed
		 }
	}
}
